# Generated by Django 2.2.6 on 2019-11-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='status',
            field=models.CharField(choices=[('DONE', 'Done'), ('IN_PROCESSING', 'In process'), ('NOT_YET_START', 'Not yet start'), ('UNFINISHED', 'Unfinished')], default='NOT_YET_START', max_length=200),
        ),
    ]
